# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sagemath/sagemath

pipelines:
  default:
    - step:
        name: PEP8
        script:
          - sudo apt-get update && sudo apt-get install -y python3-pip
          - pip3 install flake8
          - $HOME/.local/bin/flake8 estimator.py
    - step:
        name: Doctest
        script:
          - export SAGE_ROOT=`sage -c "import os; print(os.environ['SAGE_ROOT'])" | tail -1`
          - export PATH="$SAGE_ROOT/build/bin:$SAGE_ROOT/local/bin:$PATH"
          - export SAGE_PYTHON_VERSION=3
          - export SAGE_LOCAL="$SAGE_ROOT/local"
          - export DOT_SAGE=/home/sage/.sage/
          - mkdir stupid_workaround # sage doesn't like world writable but we're not allowed to change that
          - chmod 700 stupid_workaround
          - cp estimator.py stupid_workaround/
          - cp README.rst stupid_workaround/
          - cd stupid_workaround
          - PYTHONIOENCODING=UTF-8 PYTHONPATH=`pwd` sage-runtests estimator.py
          - PYTHONIOENCODING=UTF-8 PYTHONPATH=`pwd` sage-runtests README.rst
          - cd ..
