[workspace]

members = [
    "concrete",
    "concrete-npe",
    "concrete-core",
    "concrete-csprng",
    "concrete-commons",
    "concrete-tasks",
    "concrete-boolean",
    "concrete-benchmark"
]

[patch.crates-io]
concrete = {path="concrete"}
concrete-npe = {path="concrete-npe"}
concrete-core = {path="concrete-core"}
concrete-csprng = {path="concrete-csprng"}
concrete-commons = {path="concrete-commons"}
concrete-boolean = {path="concrete-boolean"}

[profile.bench]
lto = "fat"
