[workspace]

members = [
    "concrete",
    "concrete-tasks",
    "concrete-boolean",
    "concrete-shortint",
    "concrete-integer",
    "concrete-utils",
]

[profile.bench]
lto = "fat"

[profile.release]
lto = "fat"
