[tool.poetry]
name = "concrete-numpy"
version = "0.2.0-rc5"
description = "Concrete Numpy is a package containing tools to compile Numpy functions into Fully Homomorphic Encryption equivalents. Concrete Numpy goes on top of the Concrete Compiler and Concrete Library."
license = "BSD-3-Clause"
authors = [
    "Zama <hello@zama.ai>",
    "Arthur Meyre <hello@zama.ai>",
    "Umut Sahin <hello@zama.ai>",
    "Benoit Chevallier-Mames <hello@zama.ai>",
    "Jordan Frery <hello@zama.ai>",
    "Alexandre Quint <hello@zama.ai>",
    "Ayoub Benaissa <hello@zama.ai>",
    "Andrei Stoian <hello@zama.ai>",
    "Jeremy Bradley <hello@zama.ai>",
]
homepage = "https://zama.ai/concrete/"
repository = "https://github.com/zama-ai/concrete-numpy"
documentation = "http://docs.zama.ai/concrete-numpy/"
keywords = ["FHE", "homomorphic encryption", "privacy", "security"]
packages = [
    { include = "concrete" },
]
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering",
    "Topic :: Security",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Compilers",
]
readme = "pypi_readme.md"

[tool.poetry.urls]
"README" = "https://github.com/zama-ai/concrete-numpy/blob/main/README.md"
"Bug Tracker" = "https://github.com/zama-ai/concrete-numpy/issues"
"Discourse" = "https://community.zama.ai/c/concrete-numpy/7"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
networkx = "^2.6.3"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
pygraphviz = { version = "^1.7", optional = true }
Pillow = "^8.3.2"
loguru = "^0.5.3"
torch = "^1.10.0"
setuptools = "*"
concrete-compiler = "^0.1.1"

[tool.poetry.extras]
full = ["pygraphviz"]
extras = ["pygraphviz"]

[tool.poetry.dev-dependencies]
isort = "^5.9.3"
black = "^21.9b0"
pylint = "2.11.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
mypy = "0.910"
pydocstyle = "^6.1.1"
jupyter = "^1.0.0"
flake8 = "^3.9.2"
flake8-bugbear = "^21.9.2"
nbsphinx = "0.8.7"
tqdm = "^4.62.3"
psutil = "^5.8.0"
py-cpuinfo = "^8.0.0"
python-dotenv = "^0.19.0"
nbmake = "^0.9"
python-semantic-release = "7.19.2"
semver = "^2.13.0"
tomlkit = "^0.7.0"
GitPython = "^3.1.24"
pytest-xdist = "^2.4.0"
pytest-randomly = "^3.10.1"
pygments-style-tomorrow = "^1.0.0"
beautifulsoup4 = "^4.10.0"
pip-licenses = "^3.5.3"
sphinx-zama-theme = "2.0.8"
scikit-learn = "1.0.1"
pandas = "1.3.4"
pip-audit = "^1.1.1"
pytest-codeblocks = "^0.12.2"
py-progress-tracker = "^0.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:pandas not found, skipping conversion test.:ImportWarning",
    "ignore:scipy not found, skipping conversion test.:ImportWarning",
    "ignore:Matplotlib is currently using .*, which is a non-GUI backend, so cannot show the figure\\.:UserWarning"
]

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "docs/conf.py:release"
upload_to_pypi = "False"
