[package]
name = "concrete-boolean"
version = "0.1.1"
edition = "2018"
authors = ["Zama team"]
license = "BSD-3-Clause-Clear"
description = "Homomorphic Boolean circuit interface for the concrete FHE library."
homepage = "https://crates.io/crates/concrete"
documentation = "https://docs.zama.ai/concrete/boolean-lib"
repository = "https://github.com/zama-ai/concrete"
readme = "README.md"
keywords = ["fully", "homomorphic", "encryption", "fhe", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete-core = {version = "1.0.0-alpha", features=["multithread", "serde_serialize"]}
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.4"

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
