[package]
name = "concrete-utils"
version = "0.2.0"
edition = "2021"
authors = ["Zama team"]
license = "BSD-3-Clause-Clear"
description = "Internal utilities for concrete"

[dependencies]
serde = "1.0.137"
bincode = "1.3.3"
once_cell = "1.13"
